name: duseca_task_2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  font_awesome_flutter: 10.7.0
  sizer: ^3.0.4
  firebase_core: 3.6.0
  firebase_auth: ^5.3.1
  email_otp: 3.0.2
  country_flags: 3.0.0
  cloud_firestore: 5.4.4
  speed_dial_fab: ^2.3.0
  intl: 0.19.0
  shared_preferences: 2.3.2
  file_picker: 8.1.2
  flutter: 
    sdk: flutter
  firebase_storage: ^12.3.2

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

